name: Comment Test Results

on:
  workflow_run:
    workflows: ["Test Patches"]
    types: [completed]

jobs:
  comment:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request'
    
    permissions:
      pull-requests: write
      issues: write
      actions: read
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: patch-test-results
        github-token: ${{ secrets.GITHUB_TOKEN }}
        run-id: ${{ github.event.workflow_run.id }}
    
    - name: Get PR number
      id: pr
      run: |
        # Get workflow run details to find associated PR
        WORKFLOW_HEAD_BRANCH=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}" \
          | jq -r '.head_branch')

        # Find the PR that matches this branch
        PR_NUMBER=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/pulls?head=${WORKFLOW_HEAD_BRANCH}&state=open" \
          | jq -r '.[0].number')

        echo "number=$PR_NUMBER" >> $GITHUB_OUTPUT
    
    - name: Comment on PR
      if: steps.pr.outputs.number != 'null'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const buildLog = fs.readFileSync('build.log', 'utf8');
          
          // Check if patches passed
          const passed = buildLog.includes('✓ All patches') || 
                        buildLog.includes('✓ Sub-agent recursion:');
          
          // Extract relevant info from log
          const patternInfo = [];
          const patterns = buildLog.match(/.*Task (check|logic) pattern.*$/gm);
          if (patterns) {
            patternInfo.push('**Pattern Detection:**');
            patterns.forEach(p => patternInfo.push('- ' + p.trim()));
          }
          
          const body = passed ? 
            '✅ **Patches working** - Claude update compatible\n\nClosing PR as patches are still functional.' :
            `❌ **Patches BROKEN** - Need fix for new Claude version!\n\n${patternInfo.join('\n')}\n\n` +
            `Check the [workflow artifacts](https://github.com/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}) for full build log.`;
          
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: ${{ steps.pr.outputs.number }},
            body: body
          });
          
          if (passed) {
            // Close the PR if patches are working
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ steps.pr.outputs.number }},
              state: 'closed'
            });
          } else {
            // Add label if broken
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ steps.pr.outputs.number }},
              labels: ['patches-broken']
            });
          }